Universe   = container
container_image = docker://ghcr.io/sokrypton/colabfold:1.5.5-cuda12.2.2
Executable = run_afcluster_chtc.sh
Arguments = $(NAME) $(SEQ)

transfer_input_files = run_afcluster_chtc.sh, /home/waymentsteel/AFCluster-2/
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

+WantGPULab = true
+want_campus_pools = true
+want_ospool = true
request_cpus = 1
request_memory = 20GB
retry_request_memory = 40GB
request_disk = 15GB
request_gpus = 1
gpus_minimum_memory = 10000
+GPUJobLength = "short"

batch_name = afcluster
stream_output = true
output = condor_log/$(batch_name)_$(Cluster)_$(Process).out
error = condor_log/$(batch_name)_$(Cluster)_$(Process).err
log = condor_log/$(batch_name)_$(Cluster)_$(Process).log

Queue NAME,SEQ from input_seqs.csv
